name: AddictZone-Features
version: 1.0
main: net.tiam.addictzone_features.MainClass
api-version: 1.16
author: req_Ticasch
commands:
  gift:
    aliases: [rank]
  msg:
  AddictZone:
  cc:
  gm:
    aliases: [gamemode]
  fly:
  op:
  deop:
  tp:
    aliases: [tpo, teleport]
  tphere:
    aliases: [tpohere, teleporthere]
  time:
    aliases: [zeit, tageszeit]
  day:
    aliases: [tag]
  night:
    aliases: [nacht]
  bc:
    aliases: [broadcast, bcast]
  heal:
  feed:
  spy:
  vanish:
    aliases: [v]
  prefix:
  sun:
    aliases: [sonne]
  rain:
    aliases: [regen, strum, storm]
  cl:
    aliases: [chatlock]
  startinv:
    aliases: [start, setstartinv, setstartinventory]
  ec:
    aliases: [enderchest, echest]
  invsee:
  tpa:
  tpahere:
  tptoggle:
    aliases: [tpatoggle]
  tpdeny:
    aliases: [tpadeny]
  tpaaccept:
    aliases: [tpaccept]
  tpacancel:
    aliases: [tpcancel]
  reply:
    aliases: [r]
  msgtoggle:
  einfachemmy:
    aliases: [emmy]
  spawn:
  setspawn:
  restart:
    aliases: [stop]
  math:
  warp:
    aliases: [warps]
  afk:

