name: AddictZone-Features
version: 1.0
main: net.tiam.addictzone_features.MainClass
api-version: 1.16
author: req_Ticasch
commands:
  eco:
    aliases: [ecoadmin, economyadmin]
  pay:
    aliases: [bezahlen]
  bankadmin:
    aliases: [adminbank]
  limit:
    aliases: [limits, economylimit, economylimits]
  setlimit:
    aliases: [setlimits, setecolimit, setecolimits, seteconomylimit, seteconomylimits]
  economy:
  gift:
    aliases: [rank]
  msg:
  Limit:
  AddictZone:
  cc:
  gm:
    aliases: [gamemode]
  fly:
  op:
  deop:
  tp:
    aliases: [tpo, teleport]
  tphere:
    aliases: [tpohere, teleporthere]
  time:
    aliases: [zeit, tageszeit]
  day:
    aliases: [tag]
  night:
    aliases: [nacht]
  bc:
    aliases: [broadcast, bcast]
  heal:
  feed:
  spy:
  vanish:
    aliases: [v]
  prefix:
  sun:
    aliases: [sonne]
  rain:
    aliases: [regen, strum]

